// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4_IKhN0LfNXJ8W1ANmX1zJmSfDYkbbY8',
    appId: '1:996544130180:web:de2fc193caacd445e7a6d1',
    messagingSenderId: '996544130180',
    projectId: 'ai-study-buddy-29cb6',
    authDomain: 'ai-study-buddy-29cb6.firebaseapp.com',
    storageBucket: 'ai-study-buddy-29cb6.firebasestorage.app',
    measurementId: 'G-V31226VWGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGbZSXKSQS0N9sfPtQ5voMO5OOPAFz-8A',
    appId: '1:996544130180:android:6fb3b985577d4bebe7a6d1',
    messagingSenderId: '996544130180',
    projectId: 'ai-study-buddy-29cb6',
    storageBucket: 'ai-study-buddy-29cb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRNk55DEyEBeFw55tSi3VCNgSMqXiX55U',
    appId: '1:996544130180:ios:bc42daa318e1f332e7a6d1',
    messagingSenderId: '996544130180',
    projectId: 'ai-study-buddy-29cb6',
    storageBucket: 'ai-study-buddy-29cb6.firebasestorage.app',
    iosBundleId: 'com.example.aiStuddyBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRNk55DEyEBeFw55tSi3VCNgSMqXiX55U',
    appId: '1:996544130180:ios:bc42daa318e1f332e7a6d1',
    messagingSenderId: '996544130180',
    projectId: 'ai-study-buddy-29cb6',
    storageBucket: 'ai-study-buddy-29cb6.firebasestorage.app',
    iosBundleId: 'com.example.aiStuddyBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4_IKhN0LfNXJ8W1ANmX1zJmSfDYkbbY8',
    appId: '1:996544130180:web:fc2e22eabc9bf1f0e7a6d1',
    messagingSenderId: '996544130180',
    projectId: 'ai-study-buddy-29cb6',
    authDomain: 'ai-study-buddy-29cb6.firebaseapp.com',
    storageBucket: 'ai-study-buddy-29cb6.firebasestorage.app',
    measurementId: 'G-0YJV50HB3P',
  );
}
